---
 - name: create Ec2 instance
   ec2:
    region: us-west-2a
    image: ami-9abea4fb
    key_name: my-key
    instance_type: t2.micro
    wait: yes
    group: webserver
    count: 3
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: no
